# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\CalibTool\CalibrationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationForm(object):
    def setupUi(self, CalibrationForm):
        CalibrationForm.setObjectName("CalibrationForm")
        CalibrationForm.resize(784, 601)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CalibrationForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(CalibrationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(7, 7, 7, 7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_cardstate = QtWidgets.QLabel(self.groupBox)
        self.label_cardstate.setObjectName("label_cardstate")
        self.gridLayout.addWidget(self.label_cardstate, 1, 1, 1, 1)
        self.comboBox_cardname = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_cardname.setObjectName("comboBox_cardname")
        self.gridLayout.addWidget(self.comboBox_cardname, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 2)
        self.doubleSpinBox_val = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_val.setMinimum(-10.0)
        self.doubleSpinBox_val.setMaximum(20000.0)
        self.doubleSpinBox_val.setObjectName("doubleSpinBox_val")
        self.gridLayout.addWidget(self.doubleSpinBox_val, 3, 1, 1, 1)
        self.comboBox_ch = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ch.setObjectName("comboBox_ch")
        self.gridLayout.addWidget(self.comboBox_ch, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.pushButton_ouput = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ouput.setStyleSheet("QPushButton {\n"
"    height: 25px; /* 按钮高度 */\n"
"    width: 85px; /* 按钮宽度 */\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"}")
        self.pushButton_ouput.setObjectName("pushButton_ouput")
        self.gridLayout.addWidget(self.pushButton_ouput, 4, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 7)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(7, 7, 7, 7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_cali = QtWidgets.QTableWidget(CalibrationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.tableWidget_cali.setFont(font)
        self.tableWidget_cali.setObjectName("tableWidget_cali")
        self.tableWidget_cali.setColumnCount(2)
        self.tableWidget_cali.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cali.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_cali.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.tableWidget_cali, 0, 0, 1, 4)
        self.pushButton_save = QtWidgets.QPushButton(CalibrationForm)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    height: 25px; /* 按钮高度 */\n"
"    width: 85px; /* 按钮宽度 */\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_4.addWidget(self.pushButton_save, 1, 3, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(CalibrationForm)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"    height: 25px; /* 按钮高度 */\n"
"    width: 85px; /* 按钮宽度 */\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_4.addWidget(self.pushButton_clear, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_info = QtWidgets.QLabel(CalibrationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_info.setFont(font)
        self.label_info.setObjectName("label_info")
        self.gridLayout_4.addWidget(self.label_info, 1, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 8)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.gridLayout_4.setRowStretch(0, 9)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(CalibrationForm)
        QtCore.QMetaObject.connectSlotsByName(CalibrationForm)

    def retranslateUi(self, CalibrationForm):
        _translate = QtCore.QCoreApplication.translate
        CalibrationForm.setWindowTitle(_translate("CalibrationForm", "Form"))
        self.groupBox.setTitle(_translate("CalibrationForm", "校准工具"))
        self.label_6.setText(_translate("CalibrationForm", "校准板卡："))
        self.label_cardstate.setText(_translate("CalibrationForm", "TextLabel"))
        self.label_3.setText(_translate("CalibrationForm", "标准值"))
        self.label_5.setText(_translate("CalibrationForm", "板卡状态："))
        self.label.setText(_translate("CalibrationForm", "注意："))
        self.label_2.setText(_translate("CalibrationForm", "通道号："))
        self.label_4.setText(_translate("CalibrationForm", "为保证校准的准确性，标准值必须包含板卡量程范围内的最小值和最大值。"))
        self.pushButton_ouput.setText(_translate("CalibrationForm", "输出/采集"))
        item = self.tableWidget_cali.horizontalHeaderItem(0)
        item.setText(_translate("CalibrationForm", "标准值"))
        item = self.tableWidget_cali.horizontalHeaderItem(1)
        item.setText(_translate("CalibrationForm", "实测值"))
        self.pushButton_save.setText(_translate("CalibrationForm", "保存"))
        self.pushButton_clear.setText(_translate("CalibrationForm", "清空数据"))
        self.label_info.setText(_translate("CalibrationForm", "TextLabel"))
