# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xml_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XmlEditor(object):
    def setupUi(self, XmlEditor):
        XmlEditor.setObjectName("XmlEditor")
        XmlEditor.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(XmlEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.label_title = QtWidgets.QLabel(XmlEditor)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_top.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem)
        self.btn_add_element = QtWidgets.QPushButton(XmlEditor)
        self.btn_add_element.setObjectName("btn_add_element")
        self.horizontalLayout_top.addWidget(self.btn_add_element)
        self.btn_clear_all = QtWidgets.QPushButton(XmlEditor)
        self.btn_clear_all.setObjectName("btn_clear_all")
        self.horizontalLayout_top.addWidget(self.btn_clear_all)
        self.verticalLayout.addLayout(self.horizontalLayout_top)
        self.scrollArea = QtWidgets.QScrollArea(XmlEditor)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.items_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.items_layout.setObjectName("items_layout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.items_layout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_bottom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.btn_preview = QtWidgets.QPushButton(XmlEditor)
        self.btn_preview.setObjectName("btn_preview")
        self.horizontalLayout_bottom.addWidget(self.btn_preview)
        self.btn_download = QtWidgets.QPushButton(XmlEditor)
        self.btn_download.setObjectName("btn_download")
        self.horizontalLayout_bottom.addWidget(self.btn_download)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_bottom.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_bottom)

        self.retranslateUi(XmlEditor)
        QtCore.QMetaObject.connectSlotsByName(XmlEditor)

    def retranslateUi(self, XmlEditor):
        _translate = QtCore.QCoreApplication.translate
        XmlEditor.setWindowTitle(_translate("XmlEditor", "XML编辑器"))
        self.label_title.setText(_translate("XmlEditor", "XML编辑器"))
        self.btn_add_element.setText(_translate("XmlEditor", "添加元素"))
        self.btn_clear_all.setText(_translate("XmlEditor", "清空所有"))
        self.btn_preview.setText(_translate("XmlEditor", "预览XML"))
        self.btn_download.setText(_translate("XmlEditor", "下载XML"))
