# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\src\components\BusDataMonitor\monitor\dock_parser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dock_parser(object):
    def setupUi(self, dock_parser):
        dock_parser.setObjectName("dock_parser")
        dock_parser.resize(575, 780)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dock_parser)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_toggle = QtWidgets.QPushButton(dock_parser)
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout_3.addWidget(self.btn_toggle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView = QtWidgets.QTableView(dock_parser)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_index = QtWidgets.QLabel(dock_parser)
        self.label_index.setObjectName("label_index")
        self.horizontalLayout_4.addWidget(self.label_index)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(dock_parser)
        QtCore.QMetaObject.connectSlotsByName(dock_parser)

    def retranslateUi(self, dock_parser):
        _translate = QtCore.QCoreApplication.translate
        dock_parser.setWindowTitle(_translate("dock_parser", "Form"))
        self.btn_toggle.setText(_translate("dock_parser", "HEX显示"))
        self.label_index.setText(_translate("dock_parser", "序号：0"))
