# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\src\components\BusDataMonitor\monitor\dock_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dockmonitor(object):
    def setupUi(self, dockmonitor):
        dockmonitor.setObjectName("dockmonitor")
        dockmonitor.resize(571, 677)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dockmonitor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ctrl_area = QtWidgets.QHBoxLayout()
        self.ctrl_area.setObjectName("ctrl_area")
        self.btn_start = QtWidgets.QPushButton(dockmonitor)
        self.btn_start.setObjectName("btn_start")
        self.ctrl_area.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(dockmonitor)
        self.btn_stop.setObjectName("btn_stop")
        self.ctrl_area.addWidget(self.btn_stop)
        self.label_max_row = QtWidgets.QLabel(dockmonitor)
        self.label_max_row.setObjectName("label_max_row")
        self.ctrl_area.addWidget(self.label_max_row)
        self.spin_max_rows = QtWidgets.QSpinBox(dockmonitor)
        self.spin_max_rows.setObjectName("spin_max_rows")
        self.ctrl_area.addWidget(self.spin_max_rows)
        self.label_refresh = QtWidgets.QLabel(dockmonitor)
        self.label_refresh.setObjectName("label_refresh")
        self.ctrl_area.addWidget(self.label_refresh)
        self.spin_refresh = QtWidgets.QSpinBox(dockmonitor)
        self.spin_refresh.setObjectName("spin_refresh")
        self.ctrl_area.addWidget(self.spin_refresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ctrl_area.addItem(spacerItem)
        self.btn_conf = QtWidgets.QPushButton(dockmonitor)
        self.btn_conf.setObjectName("btn_conf")
        self.ctrl_area.addWidget(self.btn_conf)
        self.verticalLayout.addLayout(self.ctrl_area)
        self.tableView = QtWidgets.QTableView(dockmonitor)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.line = QtWidgets.QFrame(dockmonitor)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_count = QtWidgets.QLabel(dockmonitor)
        self.label_count.setObjectName("label_count")
        self.horizontalLayout_2.addWidget(self.label_count)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_ch = QtWidgets.QLabel(dockmonitor)
        self.label_ch.setObjectName("label_ch")
        self.horizontalLayout_2.addWidget(self.label_ch)
        self.label_TR = QtWidgets.QLabel(dockmonitor)
        self.label_TR.setObjectName("label_TR")
        self.horizontalLayout_2.addWidget(self.label_TR)
        self.label_protocol = QtWidgets.QLabel(dockmonitor)
        self.label_protocol.setObjectName("label_protocol")
        self.horizontalLayout_2.addWidget(self.label_protocol)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(dockmonitor)
        QtCore.QMetaObject.connectSlotsByName(dockmonitor)

    def retranslateUi(self, dockmonitor):
        _translate = QtCore.QCoreApplication.translate
        dockmonitor.setWindowTitle(_translate("dockmonitor", "Form"))
        self.btn_start.setText(_translate("dockmonitor", "开始"))
        self.btn_stop.setText(_translate("dockmonitor", "停止"))
        self.label_max_row.setText(_translate("dockmonitor", "最大行数:"))
        self.label_refresh.setText(_translate("dockmonitor", "刷新周期(ms):"))
        self.btn_conf.setText(_translate("dockmonitor", "通讯配置"))
        self.label_count.setText(_translate("dockmonitor", "数据量:0"))
        self.label_ch.setText(_translate("dockmonitor", "通道号：0"))
        self.label_TR.setText(_translate("dockmonitor", "传输方向："))
        self.label_protocol.setText(_translate("dockmonitor", "通讯协议："))
