# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\CustomWidgets\FormGallery.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormGallery(object):
    def setupUi(self, FormGallery):
        FormGallery.setObjectName("FormGallery")
        FormGallery.resize(751, 451)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormGallery)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(FormGallery)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(FormGallery)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_sectordash = QtWidgets.QWidget()
        self.page_sectordash.setObjectName("page_sectordash")
        self.stackedWidget.addWidget(self.page_sectordash)
        self.page_circledash = QtWidgets.QWidget()
        self.page_circledash.setObjectName("page_circledash")
        self.stackedWidget.addWidget(self.page_circledash)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)

        self.retranslateUi(FormGallery)
        QtCore.QMetaObject.connectSlotsByName(FormGallery)

    def retranslateUi(self, FormGallery):
        _translate = QtCore.QCoreApplication.translate
        FormGallery.setWindowTitle(_translate("FormGallery", "Form"))
