site_name: 正经工具箱
site_description: 基于 Python 与 PyQt5 的实用工具集合
repo_url: https://gitee.com/jjycode/py-util-demos
site_dir: site

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  favicon: ICON/fill-shit-ac.svg
  logo: ICON/fill-shit-ac.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tooltips

copyright: Copyright &copy; 2025




plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]
          options:
            show_source: true
            show_root_heading: true
            show_signature: true
            separate_signature: false

  
markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true  # 使用替代样式
  - pymdownx.superfences # 用于代码块
  - attr_list            # 用于 HTML 属性

nav:
  - 首页: index.md
  - API:
    - API/index.md
    - 自定义控件集 CustomWidgets: API/custom_widgets.md
    - 日志查看器 LogViewer: API/log_viewer.md
    - 校准工具 CalibTool: API/calib_tool.md
    - 实时数据绘图 RTDataPlot: API/rt_data_plot.md
    - 灯泡状态监控 BulbStateMonitor: API/bulb_statemonitor.md
    - 数据回放 DataReplay: API/data_replay.md
    - 资源索引查询 ResourceQuery: API/resource_query.md
    - 总线数据监控 BusDataMonitor: API/bus_data_monitor.md
    - 网络设备管理 NetManager: API/net_manager.md
    - Xml编辑器 XmlEditor: API/xml_editor.md
  - CHANGELOG: CHANGELOG.md
  - IUUSE: IUUSE.md
  - About: about.md