# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\DataReplay\DataReplay_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataReplay_Form(object):
    def setupUi(self, DataReplay_Form):
        DataReplay_Form.setObjectName("DataReplay_Form")
        DataReplay_Form.resize(1158, 814)
        self.gridLayout_2 = QtWidgets.QGridLayout(DataReplay_Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_plot = QtWidgets.QPushButton(DataReplay_Form)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.horizontalLayout_3.addWidget(self.pushButton_plot)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(DataReplay_Form)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    height: 16px;  /* 加宽 */\n"
"    background: #eee;\n"
"    border-radius: 8px;\n"
"    margin: 4px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border: 1px solid #888;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    margin: -3px 0;  /* 向上/下居中 */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #cce6ff;\n"
"    border: 1px solid #3399ff;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #3399ff;\n"
"    border: 1px solid #267acc;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 2, 1, 1, 1)
        self.treeWidget_datafile = QtWidgets.QTreeWidget(DataReplay_Form)
        self.treeWidget_datafile.setObjectName("treeWidget_datafile")
        self.gridLayout.addWidget(self.treeWidget_datafile, 1, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(DataReplay_Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_plot = QtWidgets.QGridLayout()
        self.gridLayout_plot.setObjectName("gridLayout_plot")
        self.horizontalLayout_2.addLayout(self.gridLayout_plot)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 8)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(DataReplay_Form)
        QtCore.QMetaObject.connectSlotsByName(DataReplay_Form)

    def retranslateUi(self, DataReplay_Form):
        _translate = QtCore.QCoreApplication.translate
        DataReplay_Form.setWindowTitle(_translate("DataReplay_Form", "Form"))
        self.pushButton_plot.setText(_translate("DataReplay_Form", "回放"))
        self.treeWidget_datafile.headerItem().setText(0, _translate("DataReplay_Form", "数据"))
        self.groupBox.setTitle(_translate("DataReplay_Form", "数据回放"))
