# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\DataReplay\DataReplay_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataReplay_Form(object):
    def setupUi(self, DataReplay_Form):
        DataReplay_Form.setObjectName("DataReplay_Form")
        DataReplay_Form.resize(1064, 816)
        self.groupBox = QtWidgets.QGroupBox(DataReplay_Form)
        self.groupBox.setGeometry(QtCore.QRect(310, 80, 541, 471))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_plot = QtWidgets.QGridLayout()
        self.gridLayout_plot.setObjectName("gridLayout_plot")
        self.horizontalLayout_2.addLayout(self.gridLayout_plot)
        self.treeWidget_datafile = QtWidgets.QTreeWidget(DataReplay_Form)
        self.treeWidget_datafile.setGeometry(QtCore.QRect(9, 94, 200, 713))
        self.treeWidget_datafile.setObjectName("treeWidget_datafile")
        self.pushButton_plot = QtWidgets.QPushButton(DataReplay_Form)
        self.pushButton_plot.setGeometry(QtCore.QRect(220, 90, 71, 31))
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.layoutWidget = QtWidgets.QWidget(DataReplay_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 282, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout.addWidget(self.lineEdit_filepath)
        self.pushButton_selectfile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_selectfile.setObjectName("pushButton_selectfile")
        self.horizontalLayout.addWidget(self.pushButton_selectfile)
        self.horizontalSlider = QtWidgets.QSlider(DataReplay_Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(330, 660, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(DataReplay_Form)
        QtCore.QMetaObject.connectSlotsByName(DataReplay_Form)

    def retranslateUi(self, DataReplay_Form):
        _translate = QtCore.QCoreApplication.translate
        DataReplay_Form.setWindowTitle(_translate("DataReplay_Form", "Form"))
        self.groupBox.setTitle(_translate("DataReplay_Form", "数据回放"))
        self.treeWidget_datafile.headerItem().setText(0, _translate("DataReplay_Form", "数据"))
        self.pushButton_plot.setText(_translate("DataReplay_Form", "回放"))
        self.label.setText(_translate("DataReplay_Form", "选择文件："))
        self.pushButton_selectfile.setText(_translate("DataReplay_Form", "选择"))
