# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\LogViewer\log_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_viewer(object):
    def setupUi(self, log_viewer):
        log_viewer.setObjectName("log_viewer")
        log_viewer.resize(1424, 824)
        self.horizontalLayout = QtWidgets.QHBoxLayout(log_viewer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(log_viewer)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.label_historyLogs = QtWidgets.QLabel(log_viewer)
        self.label_historyLogs.setObjectName("label_historyLogs")
        self.verticalLayout.addWidget(self.label_historyLogs)
        self.listWidget_historyLogs = QtWidgets.QListWidget(log_viewer)
        self.listWidget_historyLogs.setObjectName("listWidget_historyLogs")
        self.verticalLayout.addWidget(self.listWidget_historyLogs)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(2, 7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(log_viewer)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(log_viewer)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_logType = QtWidgets.QComboBox(log_viewer)
        self.comboBox_logType.setObjectName("comboBox_logType")
        self.comboBox_logType.addItem("")
        self.comboBox_logType.addItem("")
        self.comboBox_logType.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_logType)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(log_viewer)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.verticalLayout_2.addWidget(self.plainTextEdit_log)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)

        self.retranslateUi(log_viewer)
        QtCore.QMetaObject.connectSlotsByName(log_viewer)

    def retranslateUi(self, log_viewer):
        _translate = QtCore.QCoreApplication.translate
        log_viewer.setWindowTitle(_translate("log_viewer", "Form"))
        self.label_historyLogs.setText(_translate("log_viewer", "历史日志文件："))
        self.label.setText(_translate("log_viewer", "历史日志："))
        self.label_2.setText(_translate("log_viewer", "日志类型："))
        self.comboBox_logType.setItemText(0, _translate("log_viewer", "全部"))
        self.comboBox_logType.setItemText(1, _translate("log_viewer", "INFO"))
        self.comboBox_logType.setItemText(2, _translate("log_viewer", "ERROR"))
