# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\RTDataPlot\Dialog_Select.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Select(object):
    def setupUi(self, Dialog_Select):
        Dialog_Select.setObjectName("Dialog_Select")
        Dialog_Select.resize(400, 539)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Select)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_select = QtWidgets.QListWidget(Dialog_Select)
        self.listWidget_select.setObjectName("listWidget_select")
        self.gridLayout.addWidget(self.listWidget_select, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_Select)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Select)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Select)
        self.buttonBox.accepted.connect(Dialog_Select.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Select.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Select)

    def retranslateUi(self, Dialog_Select):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Select.setWindowTitle(_translate("Dialog_Select", "Dialog"))
        self.label.setText(_translate("Dialog_Select", "选择监控数据："))
