# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\RTDataPlot\Form_RTdata_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RTDataPlotForm(object):
    def setupUi(self, RTDataPlotForm):
        RTDataPlotForm.setObjectName("RTDataPlotForm")
        RTDataPlotForm.resize(1010, 583)
        self.horizontalLayout = QtWidgets.QHBoxLayout(RTDataPlotForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(RTDataPlotForm)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_plot = QtWidgets.QHBoxLayout()
        self.horizontalLayout_plot.setObjectName("horizontalLayout_plot")
        self.plot_widget = QtWidgets.QWidget(self.groupBox)
        self.plot_widget.setObjectName("plot_widget")
        self.horizontalLayout_plot.addWidget(self.plot_widget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_plot)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_data = QtWidgets.QGridLayout()
        self.gridLayout_data.setObjectName("gridLayout_data")
        self.gridLayout.addLayout(self.gridLayout_data, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.pushButton_select = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_select.setObjectName("pushButton_select")
        self.gridLayout.addWidget(self.pushButton_select, 0, 1, 1, 1)
        self.pushButton_screenshot = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_screenshot.setObjectName("pushButton_screenshot")
        self.gridLayout.addWidget(self.pushButton_screenshot, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.pushButton_control = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_control.setObjectName("pushButton_control")
        self.gridLayout.addWidget(self.pushButton_control, 1, 2, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 8)
        self.gridLayout.setRowStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3.setStretch(0, 7)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(RTDataPlotForm)
        QtCore.QMetaObject.connectSlotsByName(RTDataPlotForm)

    def retranslateUi(self, RTDataPlotForm):
        _translate = QtCore.QCoreApplication.translate
        RTDataPlotForm.setWindowTitle(_translate("RTDataPlotForm", "Form"))
        self.groupBox.setTitle(_translate("RTDataPlotForm", "曲线显示"))
        self.pushButton_select.setText(_translate("RTDataPlotForm", "选择监控数据"))
        self.pushButton_screenshot.setText(_translate("RTDataPlotForm", "截图"))
        self.pushButton_control.setText(_translate("RTDataPlotForm", "开始"))
