# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\RTDataPlot\Form_RTdata_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RTDataPlotForm(object):
    def setupUi(self, RTDataPlotForm):
        RTDataPlotForm.setObjectName("RTDataPlotForm")
        RTDataPlotForm.resize(999, 612)
        self.horizontalLayout = QtWidgets.QHBoxLayout(RTDataPlotForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(RTDataPlotForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_xmode = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_xmode.setObjectName("pushButton_xmode")
        self.horizontalLayout_3.addWidget(self.pushButton_xmode)
        self.pushButton_yautoscale = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_yautoscale.setObjectName("pushButton_yautoscale")
        self.horizontalLayout_3.addWidget(self.pushButton_yautoscale)
        self.pushButton_select = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout_3.addWidget(self.pushButton_select)
        self.pushButton_control = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_control.setObjectName("pushButton_control")
        self.horizontalLayout_3.addWidget(self.pushButton_control)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_plot = QtWidgets.QGridLayout()
        self.gridLayout_plot.setObjectName("gridLayout_plot")
        self.verticalLayout.addLayout(self.gridLayout_plot)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(RTDataPlotForm)
        QtCore.QMetaObject.connectSlotsByName(RTDataPlotForm)

    def retranslateUi(self, RTDataPlotForm):
        _translate = QtCore.QCoreApplication.translate
        RTDataPlotForm.setWindowTitle(_translate("RTDataPlotForm", "Form"))
        self.groupBox.setTitle(_translate("RTDataPlotForm", "曲线显示"))
        self.pushButton_xmode.setText(_translate("RTDataPlotForm", "固定X轴"))
        self.pushButton_yautoscale.setText(_translate("RTDataPlotForm", "固定Y轴"))
        self.pushButton_select.setText(_translate("RTDataPlotForm", "选择监控数据"))
        self.pushButton_control.setText(_translate("RTDataPlotForm", "开始"))
