# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\BusDataMonitor\BusDataMonitorForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BusDataMonitorForm(object):
    def setupUi(self, BusDataMonitorForm):
        BusDataMonitorForm.setObjectName("BusDataMonitorForm")
        BusDataMonitorForm.resize(1293, 920)
        self.verticalLayout = QtWidgets.QVBoxLayout(BusDataMonitorForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_txshow = QtWidgets.QPushButton(BusDataMonitorForm)
        self.pushButton_txshow.setObjectName("pushButton_txshow")
        self.horizontalLayout.addWidget(self.pushButton_txshow)
        self.pushButton_rxshow = QtWidgets.QPushButton(BusDataMonitorForm)
        self.pushButton_rxshow.setObjectName("pushButton_rxshow")
        self.horizontalLayout.addWidget(self.pushButton_rxshow)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mdiArea = QtWidgets.QMdiArea(BusDataMonitorForm)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)

        self.retranslateUi(BusDataMonitorForm)
        QtCore.QMetaObject.connectSlotsByName(BusDataMonitorForm)

    def retranslateUi(self, BusDataMonitorForm):
        _translate = QtCore.QCoreApplication.translate
        BusDataMonitorForm.setWindowTitle(_translate("BusDataMonitorForm", "Form"))
        self.pushButton_txshow.setText(_translate("BusDataMonitorForm", "发送数据监控"))
        self.pushButton_rxshow.setText(_translate("BusDataMonitorForm", "采集数据监控"))
