# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\BusDataMonitor\BusDataMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BusDataMonitor(object):
    def setupUi(self, BusDataMonitor):
        BusDataMonitor.setObjectName("BusDataMonitor")
        BusDataMonitor.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(BusDataMonitor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        BusDataMonitor.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(BusDataMonitor)
        self.toolBar.setObjectName("toolBar")
        BusDataMonitor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(BusDataMonitor)
        QtCore.QMetaObject.connectSlotsByName(BusDataMonitor)

    def retranslateUi(self, BusDataMonitor):
        _translate = QtCore.QCoreApplication.translate
        BusDataMonitor.setWindowTitle(_translate("BusDataMonitor", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("BusDataMonitor", "toolBar"))
