# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\10062\Videos\Desktop\PyUtilDemos\BusDataMonitor\DataTableForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataTableForm(object):
    def setupUi(self, DataTableForm):
        DataTableForm.setObjectName("DataTableForm")
        DataTableForm.resize(550, 634)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DataTableForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ctrl_area = QtWidgets.QHBoxLayout()
        self.ctrl_area.setObjectName("ctrl_area")
        self.btn_start = QtWidgets.QPushButton(DataTableForm)
        self.btn_start.setObjectName("btn_start")
        self.ctrl_area.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(DataTableForm)
        self.btn_stop.setObjectName("btn_stop")
        self.ctrl_area.addWidget(self.btn_stop)
        self.label_max_row = QtWidgets.QLabel(DataTableForm)
        self.label_max_row.setObjectName("label_max_row")
        self.ctrl_area.addWidget(self.label_max_row)
        self.spin_max_rows = QtWidgets.QSpinBox(DataTableForm)
        self.spin_max_rows.setObjectName("spin_max_rows")
        self.ctrl_area.addWidget(self.spin_max_rows)
        self.label_refresh = QtWidgets.QLabel(DataTableForm)
        self.label_refresh.setObjectName("label_refresh")
        self.ctrl_area.addWidget(self.label_refresh)
        self.spin_refresh = QtWidgets.QSpinBox(DataTableForm)
        self.spin_refresh.setObjectName("spin_refresh")
        self.ctrl_area.addWidget(self.spin_refresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ctrl_area.addItem(spacerItem)
        self.btn_conf = QtWidgets.QPushButton(DataTableForm)
        self.btn_conf.setObjectName("btn_conf")
        self.ctrl_area.addWidget(self.btn_conf)
        self.verticalLayout.addLayout(self.ctrl_area)
        self.tabWidget = QtWidgets.QTabWidget(DataTableForm)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtWidgets.QFrame(DataTableForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_count = QtWidgets.QLabel(DataTableForm)
        self.label_count.setObjectName("label_count")
        self.horizontalLayout_2.addWidget(self.label_count)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(DataTableForm)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(DataTableForm)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DataTableForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataTableForm)

    def retranslateUi(self, DataTableForm):
        _translate = QtCore.QCoreApplication.translate
        DataTableForm.setWindowTitle(_translate("DataTableForm", "Form"))
        self.btn_start.setText(_translate("DataTableForm", "开始"))
        self.btn_stop.setText(_translate("DataTableForm", "停止"))
        self.label_max_row.setText(_translate("DataTableForm", "最大行数:"))
        self.label_refresh.setText(_translate("DataTableForm", "刷新周期(ms):"))
        self.btn_conf.setText(_translate("DataTableForm", "通讯配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DataTableForm", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DataTableForm", "Tab 2"))
        self.label_count.setText(_translate("DataTableForm", "数据量:0"))
        self.label_2.setText(_translate("DataTableForm", "通道号：0"))
        self.label.setText(_translate("DataTableForm", "通讯协议："))
